title: NugrahaCode
logo: 
description: Complex is better than complicated
show_downloads: false
google_analytics: G-J0YH541K46
remote_theme: nugrahacode/minimal
main_page: https://nugrahacode.github.io
github:
  is_user_page: true
  is_project_page: false
 
