title: NugrahaCode
description: Complex is Better than Complicated
show_downloads: false
remote_theme: pages-themes/tactile@v0.2.0
main_page: https://nugrahacode.github.io/
github:
  is_user_page: true
  is_project_page: false
plugins:
- jekyll-remote-theme
