theme: jekyll-theme-tactile
title: NugrahaCode
description: Complex is Better than Complicated
show_downloads: false
github:
  is_user_page: true
  is_project_page: false
plugins:
- jekyll-remote-theme
